# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import csi_pb2 as csi__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in csi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPluginInfo = channel.unary_unary(
                '/csi.v1.Identity/GetPluginInfo',
                request_serializer=csi__pb2.GetPluginInfoRequest.SerializeToString,
                response_deserializer=csi__pb2.GetPluginInfoResponse.FromString,
                _registered_method=True)
        self.GetPluginCapabilities = channel.unary_unary(
                '/csi.v1.Identity/GetPluginCapabilities',
                request_serializer=csi__pb2.GetPluginCapabilitiesRequest.SerializeToString,
                response_deserializer=csi__pb2.GetPluginCapabilitiesResponse.FromString,
                _registered_method=True)
        self.Probe = channel.unary_unary(
                '/csi.v1.Identity/Probe',
                request_serializer=csi__pb2.ProbeRequest.SerializeToString,
                response_deserializer=csi__pb2.ProbeResponse.FromString,
                _registered_method=True)


class IdentityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPluginInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Probe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPluginInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginInfo,
                    request_deserializer=csi__pb2.GetPluginInfoRequest.FromString,
                    response_serializer=csi__pb2.GetPluginInfoResponse.SerializeToString,
            ),
            'GetPluginCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginCapabilities,
                    request_deserializer=csi__pb2.GetPluginCapabilitiesRequest.FromString,
                    response_serializer=csi__pb2.GetPluginCapabilitiesResponse.SerializeToString,
            ),
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=csi__pb2.ProbeRequest.FromString,
                    response_serializer=csi__pb2.ProbeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csi.v1.Identity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csi.v1.Identity', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Identity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPluginInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Identity/GetPluginInfo',
            csi__pb2.GetPluginInfoRequest.SerializeToString,
            csi__pb2.GetPluginInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Identity/GetPluginCapabilities',
            csi__pb2.GetPluginCapabilitiesRequest.SerializeToString,
            csi__pb2.GetPluginCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Identity/Probe',
            csi__pb2.ProbeRequest.SerializeToString,
            csi__pb2.ProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVolume = channel.unary_unary(
                '/csi.v1.Controller/CreateVolume',
                request_serializer=csi__pb2.CreateVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.CreateVolumeResponse.FromString,
                _registered_method=True)
        self.DeleteVolume = channel.unary_unary(
                '/csi.v1.Controller/DeleteVolume',
                request_serializer=csi__pb2.DeleteVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.DeleteVolumeResponse.FromString,
                _registered_method=True)
        self.ControllerPublishVolume = channel.unary_unary(
                '/csi.v1.Controller/ControllerPublishVolume',
                request_serializer=csi__pb2.ControllerPublishVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.ControllerPublishVolumeResponse.FromString,
                _registered_method=True)
        self.ControllerUnpublishVolume = channel.unary_unary(
                '/csi.v1.Controller/ControllerUnpublishVolume',
                request_serializer=csi__pb2.ControllerUnpublishVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.ControllerUnpublishVolumeResponse.FromString,
                _registered_method=True)
        self.ValidateVolumeCapabilities = channel.unary_unary(
                '/csi.v1.Controller/ValidateVolumeCapabilities',
                request_serializer=csi__pb2.ValidateVolumeCapabilitiesRequest.SerializeToString,
                response_deserializer=csi__pb2.ValidateVolumeCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ListVolumes = channel.unary_unary(
                '/csi.v1.Controller/ListVolumes',
                request_serializer=csi__pb2.ListVolumesRequest.SerializeToString,
                response_deserializer=csi__pb2.ListVolumesResponse.FromString,
                _registered_method=True)
        self.GetCapacity = channel.unary_unary(
                '/csi.v1.Controller/GetCapacity',
                request_serializer=csi__pb2.GetCapacityRequest.SerializeToString,
                response_deserializer=csi__pb2.GetCapacityResponse.FromString,
                _registered_method=True)
        self.ControllerGetCapabilities = channel.unary_unary(
                '/csi.v1.Controller/ControllerGetCapabilities',
                request_serializer=csi__pb2.ControllerGetCapabilitiesRequest.SerializeToString,
                response_deserializer=csi__pb2.ControllerGetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/csi.v1.Controller/CreateSnapshot',
                request_serializer=csi__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=csi__pb2.CreateSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/csi.v1.Controller/DeleteSnapshot',
                request_serializer=csi__pb2.DeleteSnapshotRequest.SerializeToString,
                response_deserializer=csi__pb2.DeleteSnapshotResponse.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/csi.v1.Controller/ListSnapshots',
                request_serializer=csi__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=csi__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.ControllerExpandVolume = channel.unary_unary(
                '/csi.v1.Controller/ControllerExpandVolume',
                request_serializer=csi__pb2.ControllerExpandVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.ControllerExpandVolumeResponse.FromString,
                _registered_method=True)
        self.ControllerGetVolume = channel.unary_unary(
                '/csi.v1.Controller/ControllerGetVolume',
                request_serializer=csi__pb2.ControllerGetVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.ControllerGetVolumeResponse.FromString,
                _registered_method=True)
        self.ControllerModifyVolume = channel.unary_unary(
                '/csi.v1.Controller/ControllerModifyVolume',
                request_serializer=csi__pb2.ControllerModifyVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.ControllerModifyVolumeResponse.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerPublishVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerUnpublishVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateVolumeCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVolumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerGetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerExpandVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerGetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerModifyVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVolume,
                    request_deserializer=csi__pb2.CreateVolumeRequest.FromString,
                    response_serializer=csi__pb2.CreateVolumeResponse.SerializeToString,
            ),
            'DeleteVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVolume,
                    request_deserializer=csi__pb2.DeleteVolumeRequest.FromString,
                    response_serializer=csi__pb2.DeleteVolumeResponse.SerializeToString,
            ),
            'ControllerPublishVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerPublishVolume,
                    request_deserializer=csi__pb2.ControllerPublishVolumeRequest.FromString,
                    response_serializer=csi__pb2.ControllerPublishVolumeResponse.SerializeToString,
            ),
            'ControllerUnpublishVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerUnpublishVolume,
                    request_deserializer=csi__pb2.ControllerUnpublishVolumeRequest.FromString,
                    response_serializer=csi__pb2.ControllerUnpublishVolumeResponse.SerializeToString,
            ),
            'ValidateVolumeCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateVolumeCapabilities,
                    request_deserializer=csi__pb2.ValidateVolumeCapabilitiesRequest.FromString,
                    response_serializer=csi__pb2.ValidateVolumeCapabilitiesResponse.SerializeToString,
            ),
            'ListVolumes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVolumes,
                    request_deserializer=csi__pb2.ListVolumesRequest.FromString,
                    response_serializer=csi__pb2.ListVolumesResponse.SerializeToString,
            ),
            'GetCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapacity,
                    request_deserializer=csi__pb2.GetCapacityRequest.FromString,
                    response_serializer=csi__pb2.GetCapacityResponse.SerializeToString,
            ),
            'ControllerGetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerGetCapabilities,
                    request_deserializer=csi__pb2.ControllerGetCapabilitiesRequest.FromString,
                    response_serializer=csi__pb2.ControllerGetCapabilitiesResponse.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=csi__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=csi__pb2.CreateSnapshotResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=csi__pb2.DeleteSnapshotRequest.FromString,
                    response_serializer=csi__pb2.DeleteSnapshotResponse.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=csi__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=csi__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'ControllerExpandVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerExpandVolume,
                    request_deserializer=csi__pb2.ControllerExpandVolumeRequest.FromString,
                    response_serializer=csi__pb2.ControllerExpandVolumeResponse.SerializeToString,
            ),
            'ControllerGetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerGetVolume,
                    request_deserializer=csi__pb2.ControllerGetVolumeRequest.FromString,
                    response_serializer=csi__pb2.ControllerGetVolumeResponse.SerializeToString,
            ),
            'ControllerModifyVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerModifyVolume,
                    request_deserializer=csi__pb2.ControllerModifyVolumeRequest.FromString,
                    response_serializer=csi__pb2.ControllerModifyVolumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csi.v1.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csi.v1.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/CreateVolume',
            csi__pb2.CreateVolumeRequest.SerializeToString,
            csi__pb2.CreateVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/DeleteVolume',
            csi__pb2.DeleteVolumeRequest.SerializeToString,
            csi__pb2.DeleteVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerPublishVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ControllerPublishVolume',
            csi__pb2.ControllerPublishVolumeRequest.SerializeToString,
            csi__pb2.ControllerPublishVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerUnpublishVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ControllerUnpublishVolume',
            csi__pb2.ControllerUnpublishVolumeRequest.SerializeToString,
            csi__pb2.ControllerUnpublishVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateVolumeCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ValidateVolumeCapabilities',
            csi__pb2.ValidateVolumeCapabilitiesRequest.SerializeToString,
            csi__pb2.ValidateVolumeCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVolumes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ListVolumes',
            csi__pb2.ListVolumesRequest.SerializeToString,
            csi__pb2.ListVolumesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/GetCapacity',
            csi__pb2.GetCapacityRequest.SerializeToString,
            csi__pb2.GetCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerGetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ControllerGetCapabilities',
            csi__pb2.ControllerGetCapabilitiesRequest.SerializeToString,
            csi__pb2.ControllerGetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/CreateSnapshot',
            csi__pb2.CreateSnapshotRequest.SerializeToString,
            csi__pb2.CreateSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/DeleteSnapshot',
            csi__pb2.DeleteSnapshotRequest.SerializeToString,
            csi__pb2.DeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ListSnapshots',
            csi__pb2.ListSnapshotsRequest.SerializeToString,
            csi__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerExpandVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ControllerExpandVolume',
            csi__pb2.ControllerExpandVolumeRequest.SerializeToString,
            csi__pb2.ControllerExpandVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerGetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ControllerGetVolume',
            csi__pb2.ControllerGetVolumeRequest.SerializeToString,
            csi__pb2.ControllerGetVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerModifyVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Controller/ControllerModifyVolume',
            csi__pb2.ControllerModifyVolumeRequest.SerializeToString,
            csi__pb2.ControllerModifyVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GroupControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GroupControllerGetCapabilities = channel.unary_unary(
                '/csi.v1.GroupController/GroupControllerGetCapabilities',
                request_serializer=csi__pb2.GroupControllerGetCapabilitiesRequest.SerializeToString,
                response_deserializer=csi__pb2.GroupControllerGetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.CreateVolumeGroupSnapshot = channel.unary_unary(
                '/csi.v1.GroupController/CreateVolumeGroupSnapshot',
                request_serializer=csi__pb2.CreateVolumeGroupSnapshotRequest.SerializeToString,
                response_deserializer=csi__pb2.CreateVolumeGroupSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteVolumeGroupSnapshot = channel.unary_unary(
                '/csi.v1.GroupController/DeleteVolumeGroupSnapshot',
                request_serializer=csi__pb2.DeleteVolumeGroupSnapshotRequest.SerializeToString,
                response_deserializer=csi__pb2.DeleteVolumeGroupSnapshotResponse.FromString,
                _registered_method=True)
        self.GetVolumeGroupSnapshot = channel.unary_unary(
                '/csi.v1.GroupController/GetVolumeGroupSnapshot',
                request_serializer=csi__pb2.GetVolumeGroupSnapshotRequest.SerializeToString,
                response_deserializer=csi__pb2.GetVolumeGroupSnapshotResponse.FromString,
                _registered_method=True)


class GroupControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GroupControllerGetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVolumeGroupSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVolumeGroupSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVolumeGroupSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GroupControllerGetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GroupControllerGetCapabilities,
                    request_deserializer=csi__pb2.GroupControllerGetCapabilitiesRequest.FromString,
                    response_serializer=csi__pb2.GroupControllerGetCapabilitiesResponse.SerializeToString,
            ),
            'CreateVolumeGroupSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVolumeGroupSnapshot,
                    request_deserializer=csi__pb2.CreateVolumeGroupSnapshotRequest.FromString,
                    response_serializer=csi__pb2.CreateVolumeGroupSnapshotResponse.SerializeToString,
            ),
            'DeleteVolumeGroupSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVolumeGroupSnapshot,
                    request_deserializer=csi__pb2.DeleteVolumeGroupSnapshotRequest.FromString,
                    response_serializer=csi__pb2.DeleteVolumeGroupSnapshotResponse.SerializeToString,
            ),
            'GetVolumeGroupSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolumeGroupSnapshot,
                    request_deserializer=csi__pb2.GetVolumeGroupSnapshotRequest.FromString,
                    response_serializer=csi__pb2.GetVolumeGroupSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csi.v1.GroupController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csi.v1.GroupController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GroupControllerGetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.GroupController/GroupControllerGetCapabilities',
            csi__pb2.GroupControllerGetCapabilitiesRequest.SerializeToString,
            csi__pb2.GroupControllerGetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVolumeGroupSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.GroupController/CreateVolumeGroupSnapshot',
            csi__pb2.CreateVolumeGroupSnapshotRequest.SerializeToString,
            csi__pb2.CreateVolumeGroupSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVolumeGroupSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.GroupController/DeleteVolumeGroupSnapshot',
            csi__pb2.DeleteVolumeGroupSnapshotRequest.SerializeToString,
            csi__pb2.DeleteVolumeGroupSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVolumeGroupSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.GroupController/GetVolumeGroupSnapshot',
            csi__pb2.GetVolumeGroupSnapshotRequest.SerializeToString,
            csi__pb2.GetVolumeGroupSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SnapshotMetadataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadataAllocated = channel.unary_stream(
                '/csi.v1.SnapshotMetadata/GetMetadataAllocated',
                request_serializer=csi__pb2.GetMetadataAllocatedRequest.SerializeToString,
                response_deserializer=csi__pb2.GetMetadataAllocatedResponse.FromString,
                _registered_method=True)
        self.GetMetadataDelta = channel.unary_stream(
                '/csi.v1.SnapshotMetadata/GetMetadataDelta',
                request_serializer=csi__pb2.GetMetadataDeltaRequest.SerializeToString,
                response_deserializer=csi__pb2.GetMetadataDeltaResponse.FromString,
                _registered_method=True)


class SnapshotMetadataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMetadataAllocated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadataDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotMetadataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetadataAllocated': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMetadataAllocated,
                    request_deserializer=csi__pb2.GetMetadataAllocatedRequest.FromString,
                    response_serializer=csi__pb2.GetMetadataAllocatedResponse.SerializeToString,
            ),
            'GetMetadataDelta': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMetadataDelta,
                    request_deserializer=csi__pb2.GetMetadataDeltaRequest.FromString,
                    response_serializer=csi__pb2.GetMetadataDeltaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csi.v1.SnapshotMetadata', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csi.v1.SnapshotMetadata', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnapshotMetadata(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMetadataAllocated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/csi.v1.SnapshotMetadata/GetMetadataAllocated',
            csi__pb2.GetMetadataAllocatedRequest.SerializeToString,
            csi__pb2.GetMetadataAllocatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadataDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/csi.v1.SnapshotMetadata/GetMetadataDelta',
            csi__pb2.GetMetadataDeltaRequest.SerializeToString,
            csi__pb2.GetMetadataDeltaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NodeStageVolume = channel.unary_unary(
                '/csi.v1.Node/NodeStageVolume',
                request_serializer=csi__pb2.NodeStageVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeStageVolumeResponse.FromString,
                _registered_method=True)
        self.NodeUnstageVolume = channel.unary_unary(
                '/csi.v1.Node/NodeUnstageVolume',
                request_serializer=csi__pb2.NodeUnstageVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeUnstageVolumeResponse.FromString,
                _registered_method=True)
        self.NodePublishVolume = channel.unary_unary(
                '/csi.v1.Node/NodePublishVolume',
                request_serializer=csi__pb2.NodePublishVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.NodePublishVolumeResponse.FromString,
                _registered_method=True)
        self.NodeUnpublishVolume = channel.unary_unary(
                '/csi.v1.Node/NodeUnpublishVolume',
                request_serializer=csi__pb2.NodeUnpublishVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeUnpublishVolumeResponse.FromString,
                _registered_method=True)
        self.NodeGetVolumeStats = channel.unary_unary(
                '/csi.v1.Node/NodeGetVolumeStats',
                request_serializer=csi__pb2.NodeGetVolumeStatsRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeGetVolumeStatsResponse.FromString,
                _registered_method=True)
        self.NodeExpandVolume = channel.unary_unary(
                '/csi.v1.Node/NodeExpandVolume',
                request_serializer=csi__pb2.NodeExpandVolumeRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeExpandVolumeResponse.FromString,
                _registered_method=True)
        self.NodeGetCapabilities = channel.unary_unary(
                '/csi.v1.Node/NodeGetCapabilities',
                request_serializer=csi__pb2.NodeGetCapabilitiesRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeGetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.NodeGetInfo = channel.unary_unary(
                '/csi.v1.Node/NodeGetInfo',
                request_serializer=csi__pb2.NodeGetInfoRequest.SerializeToString,
                response_deserializer=csi__pb2.NodeGetInfoResponse.FromString,
                _registered_method=True)


class NodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NodeStageVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeUnstageVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodePublishVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeUnpublishVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeGetVolumeStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeExpandVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeGetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeGetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NodeStageVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeStageVolume,
                    request_deserializer=csi__pb2.NodeStageVolumeRequest.FromString,
                    response_serializer=csi__pb2.NodeStageVolumeResponse.SerializeToString,
            ),
            'NodeUnstageVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeUnstageVolume,
                    request_deserializer=csi__pb2.NodeUnstageVolumeRequest.FromString,
                    response_serializer=csi__pb2.NodeUnstageVolumeResponse.SerializeToString,
            ),
            'NodePublishVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.NodePublishVolume,
                    request_deserializer=csi__pb2.NodePublishVolumeRequest.FromString,
                    response_serializer=csi__pb2.NodePublishVolumeResponse.SerializeToString,
            ),
            'NodeUnpublishVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeUnpublishVolume,
                    request_deserializer=csi__pb2.NodeUnpublishVolumeRequest.FromString,
                    response_serializer=csi__pb2.NodeUnpublishVolumeResponse.SerializeToString,
            ),
            'NodeGetVolumeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeGetVolumeStats,
                    request_deserializer=csi__pb2.NodeGetVolumeStatsRequest.FromString,
                    response_serializer=csi__pb2.NodeGetVolumeStatsResponse.SerializeToString,
            ),
            'NodeExpandVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeExpandVolume,
                    request_deserializer=csi__pb2.NodeExpandVolumeRequest.FromString,
                    response_serializer=csi__pb2.NodeExpandVolumeResponse.SerializeToString,
            ),
            'NodeGetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeGetCapabilities,
                    request_deserializer=csi__pb2.NodeGetCapabilitiesRequest.FromString,
                    response_serializer=csi__pb2.NodeGetCapabilitiesResponse.SerializeToString,
            ),
            'NodeGetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeGetInfo,
                    request_deserializer=csi__pb2.NodeGetInfoRequest.FromString,
                    response_serializer=csi__pb2.NodeGetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csi.v1.Node', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csi.v1.Node', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Node(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NodeStageVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeStageVolume',
            csi__pb2.NodeStageVolumeRequest.SerializeToString,
            csi__pb2.NodeStageVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeUnstageVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeUnstageVolume',
            csi__pb2.NodeUnstageVolumeRequest.SerializeToString,
            csi__pb2.NodeUnstageVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodePublishVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodePublishVolume',
            csi__pb2.NodePublishVolumeRequest.SerializeToString,
            csi__pb2.NodePublishVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeUnpublishVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeUnpublishVolume',
            csi__pb2.NodeUnpublishVolumeRequest.SerializeToString,
            csi__pb2.NodeUnpublishVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeGetVolumeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeGetVolumeStats',
            csi__pb2.NodeGetVolumeStatsRequest.SerializeToString,
            csi__pb2.NodeGetVolumeStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeExpandVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeExpandVolume',
            csi__pb2.NodeExpandVolumeRequest.SerializeToString,
            csi__pb2.NodeExpandVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeGetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeGetCapabilities',
            csi__pb2.NodeGetCapabilitiesRequest.SerializeToString,
            csi__pb2.NodeGetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeGetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csi.v1.Node/NodeGetInfo',
            csi__pb2.NodeGetInfoRequest.SerializeToString,
            csi__pb2.NodeGetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
