version: 2

updates:
  - package-ecosystem: "docker"
    schedule:
      interval: weekly
    directory: "/"
    commit-message:
      prefix: ":arrow_up:"
    groups:
      docker:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-packages:
        patterns: ["*"]
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: "github-actions"
    schedule:
      interval: weekly
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: ":arrow_up:"
