queue_rules:
  - name: default
    update_method: rebase
    branch_protection_injection_mode: merge
    merge_conditions:
      - check-success = ci
    queue_conditions:
      - check-success = ci
merge_queue:
  max_parallel_checks: 1
merge_protections_settings:
  reporting_method: check-runs
