repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: rawfile/csi/
      - id: ruff-format
        exclude: rawfile/csi/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: |
          (?x)^(
            deploy/.*|
            rawfile/templates/.*
          )$
      - id: end-of-file-fixer
        exclude: ^(rawfile/csi/|deploy/helm/.*/README.md)
      - id: trailing-whitespace
  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
      - id: helm-docs-built
        args:
          - --chart-search-root=deploy/helm
          - --skip-version-footer
