#!/usr/bin/env bash

slugify() {
	echo "$1" | sed -r 's/[^.a-zA-Z0-9]+/-/g'
}

echo_stderr() {
	echo -e "${1}" >&2
}

die() {
	local _return="${2:-1}"
	echo_stderr "$1"
	exit "${_return}"
}

export CI_IMAGE_NS=${CI_IMAGE_NS:-"openebs"}
export IMAGE="$CI_IMAGE_NS/rawfile-localpv"
export COMMIT=$(git rev-parse --short HEAD)
export BRANCH=${BRANCH:-$(git rev-parse --abbrev-ref HEAD)}
export IMAGE_TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || :)
export BRANCH_SLUG=$(slugify $BRANCH)

export CI_REGISTRY=${CI_REGISTRY:-"docker.io"}
export CI_IMAGE_REPO="${IMAGE}"
export CI_IMAGE_NAME="${CI_REGISTRY}/${CI_IMAGE_REPO}"
## See `docker system info --format '{{.ClientInfo.Os}}/{{.ClientInfo.Arch}}'` for default platform
export CI_IMAGE_PLATFORMS="local"
export CI_TEST="${CI_TEST:-true}"
export CI_TEST_IMAGE_TAG="${COMMIT}"
if [[ "${CI_TEST}" == "false" ]]; then
	export CI_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
else
	export TAG_SUFFIX="-ci"
fi

# override this for easy testing of a release tag
#export CI_TEST_IMAGE_TAG="v0.15.0"
#export TAG_SUFFIX=""

build-image-tag() {
	printf "%s%s" "${1}" "${TAG_SUFFIX:-}"
}

build-image-uri() {
	printf "%s:%s" "${CI_IMAGE_NAME}" "$(build-image-tag $1)"
}
