#!/usr/bin/env bash

set -ex

slugify() {
  echo "$1" | sed -r 's/[^.a-zA-Z0-9]+/-/g'
}

export IMAGE="openebs/rawfile-localpv"
export COMMIT=$(git rev-parse --short HEAD)
export BRANCH=${BRANCH:-$(git rev-parse --abbrev-ref HEAD)}
export BRANCH_SLUG=$(slugify $BRANCH)

export CI_REGISTRY="docker.io"
export CI_TAG="${COMMIT}-ci"
export CI_IMAGE_REPO="${IMAGE}"
export CI_IMAGE_URI="${CI_REGISTRY}/${CI_IMAGE_REPO}:${CI_TAG}"

command -v docker &>/dev/null || ( echo 'docker not found. exiting...'; exit 1 )

function TagAndPushImage() {
  REPO="$1"
  TAG="$2"

  IMAGE_URI="${REPO}:${TAG}${TAG_SUFFIX:-}";
  docker tag ${CI_IMAGE_URI} ${IMAGE_URI};
  echo " push ${IMAGE_URI}";
  docker push ${IMAGE_URI};
}
