apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-post-delete
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "{{ add (.Values.hookWeight | default 0) 5 }}"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}