apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-delete
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "{{ add (.Values.hookWeight | default 0) 6 }}"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ .Release.Name }}-post-delete
      restartPolicy: Never
      containers:
        - name: post-delete-job
          image: "{{ .Values.uninstaller.image.repository }}:{{ .Values.uninstaller.image.tag }}"
          imagePullPolicy: {{ .Values.uninstaller.image.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - '/scripts/post-delete.sh'
          volumeMounts:
            - name: pre-install-script
              mountPath: "/scripts"
      volumes:
        - name: pre-install-script
          configMap:
            defaultMode: 0777
            name: {{ .Release.Name }}-post-delete