apiVersion: v1
kind: Pod
metadata:
  name: {name}
  namespace: {namespace}
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  tolerations:
    - operator: Exists
  volumes:
    - name: data-dir
      hostPath:
        path: {datadir}
        type: DirectoryOrCreate
  nodeSelector: {nodeSelector}
  containers:
    - name: task
      image: {image_repository}:{image_tag}
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: data-dir
          mountPath: /data
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 100m
          memory: 100Mi
      command:
        - /bin/sh
        - -c
      args:
        - {cmd}
