{{- $cap := .Values.capabilities | default dict }}
{{- $api := $cap.apiServer | default dict }}
{{- if $api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rawfile-localpv.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rawfile-localpv.labels" . | nindent 4 }}
    component: controller
spec:
  type: ClusterIP
  {{- if $api.enabled }}
  ports:
    - port: 8080
      targetPort: 8080
      name: api-server
  {{- end }}
  selector:
    {{- include "rawfile-localpv.selectorLabels" . | nindent 4 }}
    component: controller
{{- end }}
