syntax = "proto3";

import "google/protobuf/any.proto";

service Internal {
  // Expands raw file to new size.
  rpc ExpandRawFile (ExpandRawFileRequest) returns (ExpandRawFileResponse);
  // Downloads raw file data and metadata.
  rpc GetRawFile (GetRawFileRequest) returns (GetRawFileResponse);
  // Gets stats of pools in the node
  rpc GetPoolsStats (GetPoolsStatsRequest) returns (GetPoolsStatsResponse);
  // Gets stats of the volumes for a pool
  rpc GetVolumesStat (GetVolumesStatRequest) returns (GetVolumesStatResponse);
  // Get List of tasks with status
  rpc GetNodeTasks(GetNodeTasksRequest) returns (GetNodeTasksResponse);
}

message ExpandRawFileRequest {
  // Volume ID of the raw file to be expanded.
  string volume_id = 1;
  // New size in bytes.
  int64 new_size = 2;
}

enum ExpandRawFileStatus {
  // Operation completed successfully.
  OK = 0;
  // Not enough space to expand the raw file.
  RESOURCE_EXHAUSTED = 1;
}

message ExpandRawFileResponse {
  // Is the raw file already attached?
  bool is_attached = 1;
  // Status of the expand operation.
  ExpandRawFileStatus status = 2;
}

message GetRawFileRequest {
  // Volume ID of the raw file to be downloaded.
  string volume_id = 1;
  // Whether to include file data in the response.
  bool with_data = 2;
  // Optional snapshot ID to get the raw file at a specific snapshot. will create a temporary snapshot if not provided.
  optional string snapshot_id = 3;
}
message GetRawFileResponse {
  // Metadata associated with the raw file.
  map<string, google.protobuf.Any> metadata = 1;
  // Rawfile data. Present only if with_data was true in the request.
  bytes data = 2;
}

message GetPoolsStatsRequest {
}

message PoolStat {
  // Reserved capacity of the Pool
  string reserved_capacity = 1;
  // Pool path
  string path = 2;
  // How we handle reserved_capacity
  string reserved_capacity_mode = 3;
  // Current capacity of the pool
  int64 capacity = 4;
  // Copy On Write Enabled?
  bool copy_on_write_supported = 5;
}

message GetPoolsStatsResponse {
  // Stat data, pool name is key and Stat data is value
  map<string, PoolStat> stats = 1;
}

message VolumeStat {
  // Name of the volume
  string name = 1;
  // Size of the volume (In bytes)
  int64 size = 2;
  // Copy on Write will be used or not?
  bool copy_on_write = 3;
  // Is the Volume Thin?
  bool thin_provision = 4;
  // Is the volume Ready?
  bool ready = 5;
  // Indicates that if volume has been deleted or not (with it's time in timestamp)
  optional float deleted_at = 6;
  // Volume create time (with it's time in timestamp)
  float created_at = 7;
  // Indicates when volume should get Garbage Collected (with it's time in timestamp)
  optional float gc_at = 8;
  // Name of the pool that volume has been stored on
  string storage_pool = 9;
  // Indicates that if freezefs has been enabled or not
  bool freezefs = 10;
  // Name of the backing imgfile of the volume
  string img_file = 11;
  // Physical size of the volume
  int64 physical_size = 12;
  // Logical size of the volume
  int64 logical_size = 13;
  // How many bytes in use
  int64 used = 14;
}

message GetVolumesStatRequest {
  // Name of the pool to get stats of that volumes
  string pool_name = 1;
  // Name of the volume to get stats of (Returns stats of all volumes if not provided)
  optional string volume_name = 2;
}

message GetVolumesStatResponse {
  // Stat data, volume name is key and Stat data is value
  map<string, VolumeStat> stats = 1;
}

message GetNodeTasksRequest {
}

message Task {
  // Name of the task (e.g. CreateSnapshot)
  string task = 1;
  // List of arguments that are provided for running the task
  repeated string args = 2;
  // List of Keyword args provided for tasks
  map<string, google.protobuf.Any> kwargs = 3;
  // How many times we have retried
  int64 retry_count = 4;
  // State of the task
  string state = 5;
}

message GetNodeTasksResponse {
  // map of task IDs with their state
  map<string, Task> tasks = 1;
}
