name: CI
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - develop
      - 'release/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  changes:
    uses: ./.github/workflows/docs-only.yml
  helm-ci:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.docs-only == 'false' }}
    uses: ./.github/workflows/helm-chart.yml
  k8s-ci:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.docs-only == 'false' }}
    uses: ./.github/workflows/k8s.yml
  ci:
    if: ${{ success() }}
    needs:
      - helm-ci
      - k8s-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
